### ISSUE TITLE
Crashes with exit code 139

### ISSUE THREAD

**Issue by bobburgers7** [funkyfuture/docker-rpi-syncthing#9]
Hi,

Thanks for maintaining this!  I was using the older version (prior to upgrade to 1.1.2) without any issues.  However, using the same configuration settings, when I upgrade, I now can't run the container without it crashing.  I get the error exit code 139 from what I can tell means a segmentation fault:

I am running this on Hypriot with docker version info below
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:38:25 2019
  OS/Arch:          linux/arm
  Experimental:     false

**Comment by funkyfuture** [comment]
ciao, could you please replace `set -e` with `set -ex` in the start.sh, build the image, run a container from it and post the output? warning, this may leek sensitive configuration values you may want to obfuscate.

**Comment by funkyfuture** [comment]
i added a debug option (set the environment variable `DEBUG` to `on` for the container) to the new `1.1.3` image. that does what i proposed in my previous post.

**Comment by bobburgers7** [comment]
Hi, thank you for making the debug option!  I couldn't figure out how to build it myself.

here is my run command:
docker run -d --name=syncthing -e PUID=1000 -e PGID=1000 -p 8384:8384 -p 22000:22000 -p 21027:21027/udp -v /xxxxx:/config -v /yyyyy:/yyyyyy -e CONFIG_DIR=/config funkyfuture/rpi-syncthing -e DEBUG='on'

output:
b4fe6923c8f8ab405f9ba253d14345fcd0fd63e601fd0e8e779616ad493a8bb7
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"-e\": executable file not found in $PATH": unknown.

**Comment by funkyfuture** [comment]
You need to specify environment variables before the image name.

**Comment by ramontayag** [comment]
Btw, I wasn't able to build with the latest alpine, similar to [this issue](https://stackoverflow.com/a/54824958). Setting to alpine:3.8 allows me to build the image.

**Comment by ramontayag** [comment]
I was able to deploy to my Pi by setting alpine to 3.8 👍
